// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucf5s-QomaO2JyvxJn3qAnM2NcZkMbIM',
    appId: '1:1052066387597:android:297b35ed0ab1ae5430b4c4',
    messagingSenderId: '1052066387597',
    projectId: 'storage-check-83eb4',
    storageBucket: 'storage-check-83eb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WdclEePGSwz9KVzt2tCJs2SZAxC-yoo',
    appId: '1:1052066387597:ios:5e869a25d1871bfc30b4c4',
    messagingSenderId: '1052066387597',
    projectId: 'storage-check-83eb4',
    storageBucket: 'storage-check-83eb4.appspot.com',
    androidClientId: '1052066387597-hcs9neebdu5elcihu7l6c5000729uc5s.apps.googleusercontent.com',
    iosClientId: '1052066387597-dln1chc6betk8attgaes1g3b2qn4tqrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterBoth',
  );
}
